# Generated by Django 4.0.3 on 2022-03-12 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candlecommapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Scent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fragrance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.FileField(upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candlecommapi.candle')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='candlecommapi.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CandleScent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candlecommapi.candle')),
                ('scent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candlecommapi.scent')),
            ],
        ),
        migrations.AddField(
            model_name='candle',
            name='jar_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candlecommapi.jarcolor'),
        ),
        migrations.AddField(
            model_name='candle',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candlecommapi.profile'),
        ),
        migrations.AddField(
            model_name='candle',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='candlecommapi.upload'),
        ),
    ]
