# Generated by Django 4.0.3 on 2022-03-12 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candlecommapi', '0002_candle_jarcolor_scent_upload_vote_candlescent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=140)),
                ('message', models.CharField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='candlecommapi.profile')),
            ],
        ),
    ]
