# Generated by Django 4.0.3 on 2022-03-13 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candlecommapi', '0004_vote_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='candle',
            name='scent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='candlecommapi.scent'),
        ),
    ]
