# Generated by Django 4.0.3 on 2022-03-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlecommapi', '0005_candle_scent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candle',
            name='scent',
        ),
        migrations.AddField(
            model_name='candle',
            name='scent',
            field=models.ManyToManyField(to='candlecommapi.scent'),
        ),
    ]
