# Generated by Django 4.0.3 on 2022-03-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candlecommapi', '0006_remove_candle_scent_candle_scent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candle',
            name='scent',
            field=models.ManyToManyField(null=True, to='candlecommapi.scent'),
        ),
    ]
